const allmenu = document.querySelector(".allmenu");
const brownies = document.querySelector(".brownies");
const roti = document.querySelector(".roti");
const bolu = document.querySelector(".bolu");
const menulistisi = document.querySelector(".menulist-isi");

allmenu.addEventListener("click", () => {
  menulistisi.innerHTML =
    ' <div class="menulist-isibox"> <img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2> <p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div> <div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div> </div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p> </div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"> <img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"> <h2>brownies cake</h2><p>brownies</p> </div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox">  <img src="img/download2.jpg" alt="menu-list" />          <div class="menulist-isiboxtext">            <h2>brownies cake</h2>            <p>brownies</p>          </div>        </div>        <div class="menulist-isibox">          <img src="img/download2.jpg" alt="menu-list" />          <div class="menulist-isiboxtext">            <h2>brownies cake</h2> <p>brownies</p>          </div>        </div> <div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div>';
});

brownies.addEventListener("click", () => {
  menulistisi.innerHTML =
    '<div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"> <h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" />  <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download3.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div>';
});

roti.addEventListener("click", () => {
  menulistisi.innerHTML =
    ' <div class="menulist-isibox"> <img src="img/download4.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2> <p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div> <div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div> </div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p> </div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"> <img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"> <h2>brownies cake</h2><p>brownies</p> </div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox">  <img src="img/download2.jpg" alt="menu-list" />          <div class="menulist-isiboxtext">            <h2>brownies cake</h2>            <p>brownies</p>          </div>        </div>        <div class="menulist-isibox">          <img src="img/download2.jpg" alt="menu-list" />          <div class="menulist-isiboxtext">            <h2>brownies cake</h2> <p>brownies</p>          </div>        </div> <div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div>';
});
bolu.addEventListener("click", () => {
  menulistisi.innerHTML =
    ' <div class="menulist-isibox"> <img src="img/download4.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download4.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2> <p>brownies</p></div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div> <div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div> </div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p> </div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox"> <img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"> <h2>brownies cake</h2><p>brownies</p> </div></div><div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /> <div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div><div class="menulist-isibox">  <img src="img/download2.jpg" alt="menu-list" />          <div class="menulist-isiboxtext">            <h2>brownies cake</h2>            <p>brownies</p>          </div>        </div>        <div class="menulist-isibox">          <img src="img/download2.jpg" alt="menu-list" />          <div class="menulist-isiboxtext">            <h2>brownies cake</h2> <p>brownies</p>          </div>        </div> <div class="menulist-isibox"><img src="img/download2.jpg" alt="menu-list" /><div class="menulist-isiboxtext"><h2>brownies cake</h2><p>brownies</p></div></div>';
});
